export { sql, pool } from './client';
export { CREATE_TABLES_SQL } from './schema';
export {
  getWordById,
  insertMnemonic,
  getMnemonicsByWordId,
  getExistingKeywords,
  getLanguageById,
  getPathsByLanguage,
  getPathById,
  getScenesByPathId,
  getSceneById,
  getSceneWordsWithDetails,
  getSceneMasteryForPath,
  getUserActivePath,
  upsertUserPath,
  getOverdueWordsForPreviousScenes,
  getPathWordStats,
  insertPath,
  insertScene,
  insertSceneWord,
  insertPathWord,
  insertWord,
  findWordByTextAndLanguage,
  getRandomPathWordsForQuiz,
  getFirstSceneIdForPath,
  getSceneCountForPath,
  getSceneNumberInPath,
  verifyPathAccess,
  verifySceneAccess,
  insertTutorSession,
  getTutorSessionById,
  updateTutorSession,
  insertTutorMessage,
  getTutorMessages,
  getUserKnownWords,
  getUserDueWords,
  getUserVocabWithMnemonics,
  getDueWordsForReview,
  updateWordSRS,
  getOrCreateUserWord,
  getUserStreak,
  updateUserStreak,
  getOrCreateLearnerProfile,
  updateLearnerProfile,
  getWeakWords,
  getWordsByTexts,
  insertTutorWordReviews,
  getRecentNudges,
  insertNudge,
  updateNudge,
  updateTutorSessionLearnerContext,
  insertStudioSession,
  getStudioSessionById,
  updateStudioSession,
  getActiveStudioSession,
  insertSceneDialogue,
} from './queries';
export type {
  WordWithLanguage,
  SceneWordWithDetails,
  SceneMasteryRow,
  OverdueWordRow,
  PathWordStats,
  KnownWordRow,
  VocabWithMnemonic,
  DueWordForReview,
  UserStreakData,
} from './queries';
export {
  getSceneFlowData,
  getSceneDialogues,
  getScenePhrases,
  getScenePatternExercises,
  getPhraseWords,
  getOrCreateSceneProgress,
  updateSceneProgress,
  getOrCreateUserPhrase,
  updatePhraseSRS,
  getDuePhrasesForReview,
  insertGuidedConversationSession,
} from './scene-flow-queries';
export type {
  SceneFlowData,
  DuePhraseForReview,
} from './scene-flow-queries';
