export { sql, pool } from './client';
export { CREATE_TABLES_SQL } from './schema';
export {
  getWordById,
  insertMnemonic,
  getMnemonicsByWordId,
  getExistingKeywords,
  getLanguageById,
  getPathsByLanguage,
  getPathById,
  getScenesByPathId,
  getSceneById,
  getSceneWordsWithDetails,
  getSceneMasteryForPath,
  getUserActivePath,
  upsertUserPath,
  getOverdueWordsForPreviousScenes,
  getPathWordStats,
  insertPath,
  insertScene,
  insertSceneWord,
  insertPathWord,
  insertWord,
  findWordByTextAndLanguage,
  getRandomPathWordsForQuiz,
  getSceneCountForPath,
  getSceneNumberInPath,
  verifyPathAccess,
  verifySceneAccess,
  insertTutorSession,
  getTutorSessionById,
  updateTutorSession,
  insertTutorMessage,
  getTutorMessages,
  getUserKnownWords,
  getUserDueWords,
  getUserVocabWithMnemonics,
} from './queries';
export type {
  WordWithLanguage,
  SceneWordWithDetails,
  SceneMasteryRow,
  OverdueWordRow,
  PathWordStats,
  KnownWordRow,
  VocabWithMnemonic,
} from './queries';
