import type { DailyDoseEntry } from '@/lib/daily-dose/types';

export const PT_DAILY_DOSE_PART_3: DailyDoseEntry[] = [
  {
    date: '2026-11-10',
    category: 'food',
    topic_summary:
      'Which drinks to expect at a Brazilian family meal (guaraná, orange juice, coconut water, caipirinha) and how to ask for one.',
    easy_target: `Na mesa tem guaraná, suco de laranja e água de coco. Eu quero um guaraná, por favor.`,
    easy_english: `On the table there is guaraná, orange juice and coconut water. I would like a guaraná, please.`,
    medium_target: `Em muitas casas brasileiras, a mesa tem bebidas bem geladas. Tem guaraná, suco de laranja e água de coco, e todo mundo pode beber. Quando Dona Márcia pergunta o que você quer beber, você pode dizer: Um suco de laranja, por favor. Os adultos também bebem uma caipirinha em ocasiões especiais.`,
    medium_english: `In many Brazilian homes, the table has very cold drinks. There is guaraná, orange juice and coconut water, and everyone can drink them. When Dona Márcia asks what you want to drink, you can say: An orange juice, please. The adults also have a caipirinha on special occasions.`,
    hard_target: `No almoço de domingo, a mesa costuma ficar cheia de copos e garrafas. O guaraná é um refrigerante muito brasileiro, mas os povos indígenas da Amazônia já usavam a fruta há muito tempo. Muita gente faz o suco de laranja na hora, e a água de coco é ótima no calor. A caipirinha é uma bebida de adulto, porque leva cachaça, limão, açúcar e gelo. Quando eu chegar, Dona Márcia vai perguntar o que eu quero beber. Eu já treinei a resposta: Um guaraná, por favor. Se ela oferecer uma caipirinha, eu vou dizer que hoje prefiro um suco, porque ainda estou cansado da viagem.`,
    hard_english: `At Sunday lunch, the table is usually full of glasses and bottles. Guaraná is a very Brazilian soft drink, but the Indigenous peoples of the Amazon were already using the fruit a long time ago. Many people make the orange juice fresh, and coconut water is great in the heat. Caipirinha is an adult drink, because it has cachaça, lime, sugar and ice. When I arrive, Dona Márcia is going to ask what I want to drink. I have already rehearsed the answer: A guaraná, please. If she offers me a caipirinha, I am going to say that today I prefer a juice, because I am still tired from the trip.`,
  },
  {
    date: '2026-11-11',
    category: 'small_talk',
    topic_summary:
      'How to say what you like and do not like in Portuguese, using gosto de, adoro and não gosto muito de.',
    easy_target: `Eu gosto de café com leite e adoro pão de queijo quentinho. Eu não gosto muito de pimenta.`,
    easy_english: `I like coffee with milk and I love warm cheese bread. I do not really like chilli.`,
    medium_target: `Quando a gente conhece a família, é bom dizer do que você gosta. Eu gosto muito de frutas, e adoro manga e mamão. Mas eu não gosto muito de cebola crua, porque o gosto é muito forte. Depois eu posso perguntar: E a senhora, Dona Márcia, do que gosta?`,
    medium_english: `When we meet the family, it is good to say what you like. I like fruit a lot, and I love mango and papaya. But I do not really like raw onion, because the taste is very strong. Afterwards I can ask: And you, Dona Márcia, what do you like?`,
    hard_target: `Dizer do que você gosta é uma ótima maneira de começar uma conversa. Depois de gosto, sempre vem a palavra de: eu gosto de café, do churrasco e da sua casa. Quando você gosta muito, pode dizer que adora. Se você não gosta de algo, diga que não gosta muito, porque isso soa mais educado. Se Dona Márcia servir feijoada, eu vou dizer que gostei muito, porque assim ela sabe que estou feliz. Os gostos mudam: muita gente não gostava de café quando era criança e agora não vive sem ele. Por fim, depois de falar de você, pergunte à outra pessoa: E você, do que gosta?`,
    hard_english: `Saying what you like is a great way to start a conversation. After gosto, the little word de always follows: I like coffee, I like the barbecue and I like your house. When you like something a lot, you can say that you love it. If you do not like something, say that you do not like it very much, because that sounds more polite. If Dona Márcia serves feijoada, I am going to say that I liked it a lot, because that way she knows I am happy. Tastes change: many people did not like coffee when they were children and now cannot live without it. Finally, after talking about yourself, ask the other person: And you, what do you like?`,
  },
  {
    date: '2026-11-12',
    category: 'family',
    topic_summary:
      "How to ask about your partner's childhood over old family photos, using the imperfect tense.",
    easy_target: `Dona Márcia, eu posso ver as fotos antigas de Dani? Como ela era quando era criança?`,
    easy_english: `Dona Márcia, can I see Dani's old photos? What was she like when she was a child?`,
    medium_target: `Muitas famílias guardam álbuns de fotos e gostam de mostrar para as visitas. Dona Márcia pode mostrar um álbum, e você pode perguntar: Quantos anos Dani tinha aqui? Você também pode perguntar onde ela brincava e do que ela gostava. Todo mundo vai rir e contar histórias.`,
    medium_english: `Many families keep photo albums and like to show them to visitors. Dona Márcia may show an album, and you can ask: How old was Dani in this photo? You can also ask where she used to play and what she liked. Everyone is going to laugh and tell stories.`,
    hard_target: `Quando a gente visita a família, as fotos antigas contam muitas histórias. Antigamente, as famílias guardavam as fotos em álbuns de papel, e muitos desses álbuns ainda existem. Dona Márcia pode mostrar um álbum, e você vai ver como Dani era pequena. Para falar do passado, use o imperfeito, por exemplo: Como ela era quando tinha cinco anos? Também pergunte: Onde vocês moravam naquela época, e o que faziam aos domingos? Eu já preparei essas perguntas, porque quero ouvir as histórias com calma. Se alguém contar uma história engraçada, eu vou rir e dizer: Que legal!`,
    hard_english: `When we visit the family, old photos tell many stories. In the past, families kept their photos in paper albums, and many of those albums still exist. Dona Márcia may show an album, and you will see how little Dani was. To talk about the past, use the imperfect, for example: What was she like when she was five years old? Also ask: Where did you all live back then, and what did you do on Sundays? I have already prepared these questions, because I want to listen to the stories calmly. If someone tells a funny story, I am going to laugh and say: How great!`,
  },
  {
    date: '2026-11-13',
    category: 'culture',
    topic_summary:
      'What Brazilians mean by fica à vontade and a casa é sua, and how to answer warmly.',
    easy_target: `Dona Márcia diz: Fica à vontade, Ben, a casa é sua! Eu respondo com um sorriso: Muito obrigado, Dona Márcia!`,
    easy_english: `Dona Márcia says: Make yourself at home, Ben, the house is yours! I answer with a smile: Thank you very much, Dona Márcia!`,
    medium_target: `Os brasileiros gostam de receber bem as visitas. Quando você chega, alguém pode dizer: Fica à vontade, a casa é sua. Isso não quer dizer que a casa é sua de verdade, mas que você é muito bem-vindo. Depois, muitas vezes alguém pergunta: Aceita um cafezinho?`,
    medium_english: `Brazilians like to welcome guests well. When you arrive, someone may say: Make yourself at home, the house is yours. That does not mean the house is really yours, but that you are very welcome. Afterwards, someone often asks: Would you like a little coffee?`,
    hard_target: `Receber bem é uma parte importante da cultura brasileira. Quando a visita chega, a família quer que ela se sinta em casa. Por isso, as pessoas dizem "fica à vontade" e "a casa é sua", para você se sentir bem-vindo. Antes eu não sabia o que responder quando alguém dizia isso, mas agora eu sei. O Brasil é o maior produtor de café do mundo, e oferecer um cafezinho virou um gesto normal de boas-vindas. Se eu levar flores ou um doce, Dona Márcia provavelmente vai dizer: Não precisava! Eu vou sorrir e responder: Obrigado, a casa é linda!`,
    hard_english: `Welcoming people well is an important part of Brazilian culture. When a guest arrives, the family wants them to feel at home. That is why people say "make yourself at home" and "the house is yours", so that you feel welcome. Before, I did not know what to answer when someone said this, but now I do. Brazil is the biggest coffee producer in the world, and offering a little coffee has become a normal welcome gesture. If I bring flowers or a sweet, Dona Márcia will probably say: You did not need to! I am going to smile and answer: Thank you, the house is lovely!`,
  },
  {
    date: '2026-11-14',
    category: 'food',
    topic_summary:
      'How to answer Mais um pouquinho? kindly when a host offers second helpings, whether you are full or want more.',
    easy_target: `Dona Márcia pergunta: Mais um pouquinho? Eu respondo com um sorriso: Estou satisfeito, obrigado, mas estava uma delícia!`,
    easy_english: `Dona Márcia asks: A little more? I answer with a smile: I am full, thank you, but it was delicious!`,
    medium_target: `Em muitas casas brasileiras, a dona da casa gosta de ver todo mundo comendo bem. Por isso, ela pergunta várias vezes: Mais um pouquinho? Se você já comeu bastante, pode dizer: Estou satisfeito, obrigado, mas estava tudo muito bom. Se você quer mais, diga: Só um pouquinho, por favor.`,
    medium_english: `In many Brazilian homes, the lady of the house likes to see everyone eating well. That is why she asks several times: A little more? If you have already eaten enough, you can say: I am full, thank you, but everything was very good. If you want more, say: Just a little, please.`,
    hard_target: `No Brasil, oferecer comida é uma forma de carinho. Muitas vezes a dona da casa pergunta: Mais um pouquinho? Se você disser não uma vez, ela pode insistir mais uma ou duas vezes, e isso é só simpatia. Eu já aprendi que recusar com um sorriso funciona melhor do que só dizer não. Por isso, quando eu estiver satisfeito, vou dizer com um sorriso: Estou satisfeito, obrigado, estava uma delícia! Repare que a gente usa estava, no passado, porque você já comeu. Se eu quiser repetir, vou pedir só um pouquinho, para ter espaço para a sobremesa.`,
    hard_english: `In Brazil, offering food is a way of showing affection. The lady of the house often asks: A little more? If you say no once, she may insist one or two more times, and that is just friendliness. I have already learned that refusing with a smile works better than just saying no. So when I am full, I am going to say with a smile: I am full, thank you, it was delicious! Notice that we use estava, in the past, because you have already eaten. If I want seconds, I am going to ask for just a little, to leave room for dessert.`,
  },
  {
    date: '2026-11-15',
    category: 'holidays',
    topic_summary:
      'The Proclamação da República on 15 November 1889, when Brazil stopped being an empire and became a republic.',
    easy_target: `Hoje é 15 de novembro, um feriado no Brasil. É o dia da Proclamação da República, e muita gente descansa em casa.`,
    easy_english: `Today is 15 November, a holiday in Brazil. It is the day of the Proclamation of the Republic, and many people rest at home.`,
    medium_target: `Até 1889, o Brasil era um império, e o imperador era Dom Pedro Segundo. No dia 15 de novembro de 1889, o marechal Deodoro da Fonseca proclamou a República. Depois disso, o Brasil passou a ter um presidente em vez de um imperador. Hoje esse dia é feriado nacional, e muita gente aproveita para descansar com a família.`,
    medium_english: `Until 1889, Brazil was an empire, and the emperor was Dom Pedro the Second. On 15 November 1889, Marshal Deodoro da Fonseca proclaimed the Republic. After that, Brazil began to have a president instead of an emperor. Today that day is a national holiday, and many people take the chance to rest with their family.`,
    hard_target: `Em 15 de novembro de 1889, o Brasil deixou de ser um império e virou uma república. Até aquele dia, o país era governado por Dom Pedro Segundo, um imperador que estava no trono desde criança. Naquela manhã, o marechal Deodoro da Fonseca liderou militares no Rio de Janeiro, que era a capital. A família imperial saiu do país poucos dias depois e foi morar na Europa. Deodoro foi o primeiro presidente da república brasileira. Hoje, o dia 15 de novembro é feriado nacional, e muita gente descansa ou almoça com a família. Quando eu estiver em São Paulo, vou perguntar como a família costuma passar os feriados.`,
    hard_english: `On 15 November 1889, Brazil stopped being an empire and became a republic. Until that day, the country was governed by Dom Pedro the Second, an emperor who had been on the throne since he was a child. That morning, Marshal Deodoro da Fonseca led soldiers in Rio de Janeiro, which was the capital. The imperial family left the country a few days later and went to live in Europe. Deodoro was the first president of the Brazilian republic. Today, 15 November is a national holiday, and many people rest or have lunch with their family. When I am in São Paulo, I am going to ask how the family usually spends the holidays.`,
  },
  {
    date: '2026-11-16',
    category: 'language',
    topic_summary:
      'Polite phrases to ask people to repeat or slow down when they speak fast.',
    easy_target: `Desculpa, eu ainda estou aprendendo português e não entendi. Pode falar mais devagar, por favor?`,
    easy_english: `Sorry, I am still learning Portuguese and I did not understand. Can you speak more slowly, please?`,
    medium_target: `Em uma mesa brasileira, muita gente fala ao mesmo tempo, e a conversa fica rápida. Isso é normal, e ninguém fica chateado quando você pede ajuda. Você pode dizer: Pode repetir, por favor? Ou então: Pode falar mais devagar? Se uma palavra é nova, pergunte: O que quer dizer essa palavra?`,
    medium_english: `At a Brazilian table, many people talk at the same time, and the conversation gets fast. That is normal, and nobody gets annoyed when you ask for help. You can say: Can you repeat, please? Or else: Can you speak more slowly? If a word is new, ask: What does this word mean?`,
    hard_target: `Na primeira conversa com a família de Dani, você vai ouvir muitas frases rápidas. Não tem problema, porque todo mundo sabe que você está aprendendo. Se você não ouvir bem, diga: Pode repetir, por favor? Se a pessoa falar rápido demais, peça: Pode falar mais devagar? Nas últimas semanas, eu aprendi muitas palavras novas, mas as pessoas ainda falam mais rápido do que eu consigo acompanhar. Antes eu achava que precisava entender tudo; agora sei que uma pergunta é melhor do que um silêncio. Vou pedir ajuda quantas vezes for preciso, sempre com um sorriso e um obrigado.`,
    hard_english: `In the first conversation with Dani's family, you are going to hear many fast sentences. It is no problem, because everyone knows that you are learning. If you cannot hear well, say: Can you repeat, please? If the person speaks too fast, ask: Can you speak more slowly? In recent weeks I have learned many new words, but people still speak faster than I can follow. I used to think I needed to understand everything; now I know that a question is better than a silence. I am going to ask for help as many times as necessary, always with a smile and a thank you.`,
  },
  {
    date: '2026-11-17',
    category: 'music_tv',
    topic_summary:
      'Novelas, the evening soap operas that many Brazilian families watch and talk about together.',
    easy_target: `Depois do jantar, muita gente vê a novela na televisão. Eu pergunto: Quem é o vilão?`,
    easy_english: `After dinner, many people watch the soap opera on television. I ask: Who is the villain?`,
    medium_target: `A novela é uma série brasileira que passa quase todos os dias, à noite. Muitas famílias assistem à novela juntas, depois do jantar. A história costuma ter um casal, um vilão e muitos segredos. No dia seguinte, todo mundo fala do capítulo, e você pode perguntar: O que aconteceu ontem?`,
    medium_english: `The novela is a Brazilian series that airs almost every day, in the evening. Many families watch it together, after dinner. The story usually has a couple, a villain and many secrets. The next day, everyone talks about the episode, and you can ask: What happened yesterday?`,
    hard_target: `A novela é uma parte importante da televisão brasileira há muitas décadas. As novelas ganham o nome do horário em que passam: a das seis, a das sete e a das nove. Cada uma dura alguns meses e termina com um último capítulo que muita gente espera com ansiedade. Algumas novelas brasileiras já passaram na televisão de vários países. Depois de cada capítulo, muita gente comentava a história no trabalho e na escola. Se a família estiver vendo uma novela quando eu chegar, vou sentar com todo mundo e tentar entender a história. Uma pergunta simples ajuda muito: Quem é o vilão?`,
    hard_english: `The novela has been an important part of Brazilian television for many decades. Novelas get their name from the time they air: the one at six, the one at seven and the one at nine. Each one lasts a few months and ends with a final episode that many people wait for eagerly. Some Brazilian novelas have already been shown on television in several countries. After each episode, many people used to discuss the story at work and at school. If the family is watching a novela when I arrive, I am going to sit with everyone and try to understand the story. A simple question helps a lot: Who is the villain?`,
  },
  {
    date: '2026-11-18',
    category: 'music_tv',
    topic_summary:
      'The kinds of Brazilian music you might hear at a family party: samba, MPB and sertanejo.',
    easy_target: `Na festa de família, tem música: samba, MPB e sertanejo. Eu gosto de samba, e você?`,
    easy_english: `At the family party, there is music: samba, MPB and sertanejo. I like samba, and you?`,
    medium_target: `Muitas festas de família têm música ao vivo ou uma caixa de som. O samba é alegre e tem pandeiro e cavaquinho. A MPB, Música Popular Brasileira, tem artistas como Caetano Veloso e Elis Regina. O sertanejo é muito popular hoje, e muita gente canta junto.`,
    medium_english: `Many family parties have live music or a speaker. Samba is cheerful and has the pandeiro, a kind of tambourine, and the cavaquinho, a small guitar. MPB, Música Popular Brasileira, has artists like Caetano Veloso and Elis Regina. Sertanejo is very popular today, and many people sing along.`,
    hard_target: `Numa festa de família, quase sempre tem música. O samba nasceu da cultura afro-brasileira e usa instrumentos como o pandeiro e o cavaquinho. A MPB, que quer dizer Música Popular Brasileira, tem artistas como Caetano Veloso, Gilberto Gil, Chico Buarque e Elis Regina. O sertanejo começou no interior do país, com duplas de cantores, e hoje é um dos estilos mais ouvidos. Antigamente, as famílias ouviam discos e rádio, mas agora muita gente coloca a música no celular. Quando eu chegar, vou perguntar: Qual é a música favorita da família? Se tocar um samba, eu vou tentar cantar junto, mesmo sem saber a letra.`,
    hard_english: `At a family party, there is almost always music. Samba was born from Afro-Brazilian culture and uses instruments like the pandeiro and the cavaquinho. MPB, which means Música Popular Brasileira, includes artists like Caetano Veloso, Gilberto Gil, Chico Buarque and Elis Regina. Sertanejo began in the countryside, with duos of singers, and today it is one of the most listened-to styles. In the past, families listened to records and the radio, but now many people play music on their phones. When I arrive, I am going to ask: What is the family's favourite music? If a samba plays, I am going to try to sing along, even without knowing the words.`,
  },
  {
    date: '2026-11-19',
    category: 'culture',
    topic_summary:
      "São Paulo's Japanese-Brazilian community, from the first immigrants in 1908 to the Liberdade neighbourhood today.",
    easy_target: `São Paulo tem uma grande comunidade japonesa. Eu quero comer comida japonesa no bairro da Liberdade.`,
    easy_english: `São Paulo has a large Japanese community. I want to eat Japanese food in the Liberdade neighbourhood.`,
    medium_target: `O Brasil tem a maior comunidade de origem japonesa fora do Japão, e muitos vivem em São Paulo. Os primeiros imigrantes chegaram de navio em 1908 e trabalharam em fazendas de café. No bairro da Liberdade, você vê lanternas vermelhas e pode comer yakisoba, temaki e outros pratos japoneses. Muitos paulistanos têm sobrenome japonês, e isso faz parte da cidade.`,
    medium_english: `Brazil has the largest community of Japanese origin outside Japan, and many of them live in São Paulo. The first immigrants arrived by ship in 1908 and worked on coffee farms. In the Liberdade neighbourhood, you see red lanterns and can eat yakisoba, temaki and other Japanese dishes. Many people from São Paulo have a Japanese surname, and that is part of the city.`,
    hard_target: `São Paulo tem uma história muito ligada à imigração. Em 1908, um navio chamado Kasato Maru levou os primeiros imigrantes japoneses ao porto de Santos. Eles trabalharam em fazendas de café, onde a vida era difícil e o trabalho era pesado. Com o tempo, muitas famílias se mudaram para a capital e abriram lojas e restaurantes. Hoje, o bairro da Liberdade é o lugar mais conhecido dessa cultura, com lanternas vermelhas e uma feira nos fins de semana. Se a gente for lá, eu vou provar um yakisoba e olhar as lojinhas. É curioso aprender português numa cidade com tanta influência japonesa.`,
    hard_english: `São Paulo has a history closely tied to immigration. In 1908, a ship called the Kasato Maru brought the first Japanese immigrants to the port of Santos. They worked on coffee farms, where life was hard and the work was heavy. Over time, many families moved to the capital and opened shops and restaurants. Today, the Liberdade neighbourhood is the best-known place for this culture, with red lanterns and a market at weekends. If we go there, I am going to try a yakisoba and look at the little shops. It is curious to learn Portuguese in a city with so much Japanese influence.`,
  },
  {
    date: '2026-11-20',
    category: 'holidays',
    topic_summary:
      'Dia da Consciência Negra on 20 November, a national holiday since 2024 that remembers Zumbi dos Palmares.',
    easy_target: `Hoje é 20 de novembro, Dia da Consciência Negra. É feriado no Brasil e é um dia para lembrar Zumbi dos Palmares.`,
    easy_english: `Today is 20 November, Black Awareness Day. It is a holiday in Brazil and a day to remember Zumbi dos Palmares.`,
    medium_target: `O Dia da Consciência Negra é feriado nacional desde 2024. Ele lembra Zumbi dos Palmares, um líder do Quilombo dos Palmares, no Nordeste do Brasil. Um quilombo era uma comunidade de pessoas que fugiram da escravidão. Nesse dia, centros culturais fazem eventos sobre a história e a cultura afro-brasileira.`,
    medium_english: `Black Awareness Day has been a national holiday since 2024. It remembers Zumbi dos Palmares, a leader of the Quilombo dos Palmares, in the Northeast of Brazil. A quilombo was a community of people who escaped slavery. On this day, cultural centres hold events about Afro-Brazilian history and culture.`,
    hard_target: `O dia 20 de novembro é o Dia da Consciência Negra, e desde 2024 é feriado nacional. A data lembra Zumbi dos Palmares, que morreu em 20 de novembro de 1695. Ele foi um líder do Quilombo dos Palmares, uma comunidade no Nordeste onde viviam pessoas que fugiram da escravidão. Palmares durou quase um século, e por isso Zumbi virou um símbolo de resistência. O Brasil foi o último país das Américas a acabar com a escravidão, em 1888. Hoje muita gente usa esse dia para falar de história, respeito e igualdade. Quando eu estiver em São Paulo, vou ler mais sobre essa história e perguntar o que este dia significa para a família.`,
    hard_english: `20 November is Black Awareness Day, and since 2024 it has been a national holiday. The date remembers Zumbi dos Palmares, who died on 20 November 1695. He was a leader of the Quilombo dos Palmares, a community in the Northeast where people who escaped slavery lived. Palmares lasted almost a century, and that is why Zumbi became a symbol of resistance. Brazil was the last country in the Americas to abolish slavery, in 1888. Today many people use this day to talk about history, respect and equality. When I am in São Paulo, I am going to read more about this history and ask what this day means to the family.`,
  },
  {
    date: '2026-11-21',
    category: 'food',
    topic_summary:
      'Salgadinhos at Brazilian parties: coxinha, pão de queijo, esfiha and kibe.',
    easy_target: `Na festa tem salgadinhos: coxinha, pão de queijo e kibe. Eu quero uma coxinha, por favor!`,
    easy_english: `At the party there are savoury snacks: coxinha, cheese bread and kibe. I would like a coxinha, please!`,
    medium_target: `Em uma festa brasileira, os salgadinhos vêm em bandejas e todo mundo pega com a mão. A coxinha é de frango, tem massa macia e é frita. O pão de queijo vem de Minas Gerais e é feito com queijo. A esfiha e o kibe têm origem árabe, e São Paulo adora os dois.`,
    medium_english: `At a Brazilian party, the savoury snacks come on trays and everyone picks them up by hand. The coxinha is filled with chicken, has a soft dough and is fried. Pão de queijo comes from Minas Gerais and is made with cheese. Esfiha and kibe have Arab origins, and São Paulo loves both.`,
    hard_target: `Nas festas brasileiras, os salgadinhos são pequenos lanches salgados que passam em bandejas. Muita gente come com a mão, com um guardanapo de papel. A coxinha é a mais famosa, uma massa frita em forma de gota, recheada com frango desfiado. O pão de queijo nasceu em Minas Gerais e é feito com polvilho e queijo. Já a esfiha e o kibe chegaram com imigrantes árabes e hoje fazem parte da comida paulistana. Em muitas famílias, todo mundo ajudava a fazer os salgadinhos na véspera da festa. Se eu for a uma festa, vou provar um de cada. Vou comer devagar, porque depois ainda vem o bolo.`,
    hard_english: `At Brazilian parties, salgadinhos are small savoury snacks that go around on trays. Many people eat with their hands, with a paper napkin. The coxinha is the most famous, a fried dough shaped like a drop, filled with shredded chicken. Pão de queijo was born in Minas Gerais and is made with cassava starch and cheese. Esfiha and kibe, on the other hand, arrived with Arab immigrants and are now part of São Paulo food. In many families, everyone used to help make the salgadinhos the day before the party. If I go to a party, I am going to try one of each. I am going to eat slowly, because the cake still comes afterwards.`,
  },
  {
    date: '2026-11-22',
    category: 'family',
    topic_summary:
      'Offering to help in the kitchen with Posso ajudar? and how hosts often answer.',
    easy_target: `Dona Márcia, posso ajudar na cozinha? Eu posso lavar a louça ou pôr a mesa.`,
    easy_english: `Dona Márcia, can I help in the kitchen? I can wash the dishes or set the table.`,
    medium_target: `Depois do almoço, é sempre bom oferecer ajuda na cozinha. Você pode dizer: Posso ajudar? Às vezes a dona da casa responde: Não precisa, pode ficar à vontade. Mas você pode insistir com carinho: Eu faço questão! Assim ela vê que você é educado e quer participar.`,
    medium_english: `After lunch, it is always good to offer help in the kitchen. You can say: Can I help? Sometimes the lady of the house answers: You do not need to, just make yourself comfortable. But you can insist warmly: I insist! That way she sees that you are polite and want to take part.`,
    hard_target: `No Brasil, oferecer ajuda depois da refeição é sempre um gesto muito apreciado. Você pode se levantar e perguntar: Posso ajudar a tirar a mesa? É comum a dona da casa dizer que não precisa, porque não quer dar trabalho à visita. Se isso acontecer, sorria e diga com carinho: Eu faço questão! Depois, você pode levar os pratos para a pia, secar os copos ou guardar a comida na geladeira. Depois de um almoço de família, a cozinha ficava cheia de gente conversando enquanto todo mundo lavava a louça. Eu já aprendi as palavras principais: louça, pia, prato e copo. Assim eu vou ajudar e ainda vou conversar mais com Dona Márcia.`,
    hard_english: `In Brazil, offering help after the meal is always a much appreciated gesture. You can get up and ask: Can I help clear the table? It is common for the lady of the house to say there is no need, because she does not want to give a guest work. If that happens, smile and say warmly: I insist! Afterwards, you can take the plates to the sink, dry the glasses or put the food away in the fridge. After a family lunch, the kitchen would fill up with people chatting while everyone washed the dishes. I have already learned the main words: dishes, sink, plate and glass. That way I will help and also chat more with Dona Márcia.`,
  },
  {
    date: '2026-11-23',
    category: 'small_talk',
    topic_summary:
      'How to talk about your work with Eu trabalho com and Eu trabalho de casa.',
    easy_target: `Eu moro em Bali, trabalho com tecnologia e trabalho de casa. E você, trabalha com o quê?`,
    easy_english: `I live in Bali, I work in technology and I work from home. And you, what do you do for work?`,
    medium_target: `Na mesa, Seu Roberto pode perguntar: Você trabalha com quê? Você pode responder: Eu trabalho com tecnologia. Se você trabalha em casa, diga: Eu trabalho de casa. Também é comum dizer home office, porque muita gente usa essa palavra em inglês. Depois, pergunte também: E o senhor, trabalha com o quê?`,
    medium_english: `At the table, Seu Roberto may ask: What do you do for work? You can answer: I work in technology. If you work at home, say: I work from home. It is also common to say home office, because many people use that word in English. Afterwards, ask as well: And you, sir, what do you do for work?`,
    hard_target: `Em uma conversa de família, uma das primeiras perguntas costuma ser: Você trabalha com quê? Para responder, use a frase eu trabalho com e depois diga a sua área. Eu trabalho com tecnologia e, como moro em Bali, trabalho de casa. Muitos brasileiros também dizem home office, porque essa expressão em inglês é muito comum no país. Antes, muita gente trabalhava só em escritórios, mas nos últimos anos o home office cresceu muito. Se Seu Roberto perguntar sobre o meu trabalho, vou explicar com frases simples. Depois eu vou perguntar a ele: E o senhor, com o que trabalha?`,
    hard_english: `In a family conversation, one of the first questions is usually: What do you do for work? To answer, use the phrase eu trabalho com and then say your field. I work in technology and, since I live in Bali, I work from home. Many Brazilians also say home office, because that English expression is very common in the country. In the past, many people worked only in offices, but in recent years working from home has grown a lot. If Seu Roberto asks about my work, I am going to explain it with simple sentences. Afterwards I am going to ask him: And you, sir, what do you do for work?`,
  },
  {
    date: '2026-11-24',
    category: 'culture',
    topic_summary:
      'Pets as family members in Brazilian homes, and what to say to the family dog and its owners.',
    easy_target: `Muitas famílias brasileiras têm um cachorro ou um gato. Eu pergunto: Qual é o nome dele?`,
    easy_english: `Many Brazilian families have a dog or a cat. I ask: What is his name?`,
    medium_target: `Para muitos brasileiros, o cachorro faz parte da família. Quando você chega a uma casa com cachorro, muitas vezes ele corre até a porta e quer brincar com você. Você pode perguntar: Ele é manso? Se ele gosta de você, a família fica feliz, e você faz amizade mais rápido.`,
    medium_english: `For many Brazilians, the dog is part of the family. When you arrive at a house with a dog, he often runs to the door and wants to play with you. You can ask: Is he gentle? If he likes you, the family is happy, and you make friends faster.`,
    hard_target: `No Brasil, muita gente trata o cachorro ou o gato como um membro da família. Algumas pessoas chamam o cachorro de filho de quatro patas e falam dele com muito carinho. Antes, muitos cachorros moravam só no quintal, mas hoje vivem dentro de casa. Muitas famílias adotaram animais que encontraram na rua, e hoje eles fazem parte da casa. Se a família de Dani tiver um cachorro, ele vai me receber na porta, cheirar as minhas mãos e pedir carinho. Eu já aprendi as perguntas úteis: qual é o nome dele, quantos anos ele tem e se ele é manso. Se ele gostar de mim, vou ganhar um amigo novo antes do almoço.`,
    hard_english: `In Brazil, many people treat the dog or the cat as a member of the family. Some people call their dog a four-legged child and talk about him with great affection. In the past, many dogs lived only in the yard, but today they live inside the house. Many families have adopted animals they found on the street, and today those animals are part of the home. If Dani's family has a dog, he is going to greet me at the door, sniff my hands and ask for affection. I have already learned the useful questions: what his name is, how old he is and whether he is gentle. If he likes me, I am going to gain a new friend before lunch.`,
  },
  {
    date: '2026-11-25',
    category: 'food',
    topic_summary:
      'Açaí, from an Amazon fruit eaten with fish and manioc flour to the sweet cold bowl sold in São Paulo snack bars.',
    easy_target: `O açaí vem da Amazônia. Eu gosto de açaí gelado na tigela, com banana e granola.`,
    easy_english: `Açaí comes from the Amazon. I like cold açaí in a bowl, with banana and granola.`,
    medium_target: `O açaí é uma fruta pequena, roxa e escura, da Amazônia. No Pará, um estado da Amazônia, muita gente come açaí com peixe e farinha. Em São Paulo, o açaí é um lanche doce e gelado. A lanchonete serve o açaí na tigela, e você escolhe banana, granola ou morango.`,
    medium_english: `Açaí is a small, purple, dark fruit from the Amazon. In Pará, a state in the Amazon, many people eat açaí with fish and manioc flour. In São Paulo, açaí is a sweet, cold snack. The snack bar serves the açaí in a bowl, and you choose banana, granola or strawberry.`,
    hard_target: `O açaí é o fruto de uma palmeira da Amazônia, pequeno, roxo e muito escuro. Por muito tempo, ele foi um alimento típico do Norte do Brasil, e as pessoas comiam açaí com peixe e farinha de mandioca. Nas últimas décadas, o açaí chegou ao Sudeste e virou um lanche popular entre jovens e atletas. Hoje, em São Paulo, muitas lanchonetes vendem açaí na tigela, sempre bem gelado. Em geral, as pessoas colocam banana, granola e leite condensado por cima, e a mistura fica doce e cremosa. O açaí já conquistou muita gente fora do Brasil, e eu quero provar a versão paulistana. Depois de um dia quente, vou pedir um açaí para dividir com Dani.`,
    hard_english: `Açaí is the fruit of a palm tree from the Amazon, small, purple and very dark. For a long time, it was a typical food of the North of Brazil, and people ate açaí with fish and manioc flour. In recent decades, açaí reached the Southeast and became a popular snack among young people and athletes. Today, in São Paulo, many snack bars sell açaí in a bowl, always very cold. In general, people put banana, granola and condensed milk on top, and the mixture becomes sweet and creamy. Açaí has already won over many people outside Brazil, and I want to try the São Paulo version. After a hot day, I am going to order an açaí to share with Dani.`,
  },
  {
    date: '2026-11-26',
    category: 'language',
    topic_summary:
      'How gender works in Portuguese: obrigado versus obrigada, cansado versus cansada, bem-vindo versus bem-vinda.',
    easy_target: `Um homem diz obrigado, e uma mulher diz obrigada. Eu sou homem, então eu digo obrigado.`,
    easy_english: `A man says obrigado, and a woman says obrigada. I am a man, so I say obrigado.`,
    medium_target: `Em português, muitas palavras mudam quando falamos de um homem ou de uma mulher. Eu sou homem, então digo obrigado, cansado e satisfeito. Dani diz obrigada, cansada e satisfeita. A palavra bem-vindo muda com quem chega: Dona Márcia vai dizer bem-vindo para mim e bem-vinda para uma mulher.`,
    medium_english: `In Portuguese, many words change when we talk about a man or a woman. I am a man, so I say obrigado, cansado and satisfeito. Dani says obrigada, cansada and satisfeita. The word bem-vindo changes with whoever arrives: Dona Márcia is going to say bem-vindo to me and bem-vinda to a woman.`,
    hard_target: `Em português, muitas palavras têm uma forma masculina e uma feminina. Quando você agradece, a palavra depende de quem fala, e não de quem escuta. Por isso eu sempre digo obrigado, até quando falo com Dona Márcia. Adjetivos como cansado e satisfeito também descrevem quem fala, então eu digo estou cansado, e Dani diz estou cansada. Bem-vindo funciona ao contrário, porque muda de acordo com a pessoa que chega. No começo, eu confundia obrigado e obrigada, mas hoje aprendi uma regra simples: sou homem, então uso as formas masculinas. Quando eu chegar, Dona Márcia vai dizer: Bem-vindo, Ben! E eu vou responder: Obrigado, estou feliz, mesmo cansado da viagem!`,
    hard_english: `In Portuguese, many words have a masculine form and a feminine form. When you say thank you, the word depends on who is speaking, not on who is listening. That is why I always say obrigado, even when I talk to Dona Márcia. Adjectives like cansado and satisfeito also describe the speaker, so I say estou cansado, and Dani says estou cansada. Bem-vindo works the other way round, because it changes according to the person who arrives. At the beginning I used to mix up obrigado and obrigada, but today I learned a simple rule: I am a man, so I use the masculine forms. When I arrive, Dona Márcia is going to say: Welcome, Ben! And I am going to answer: Thank you, I am happy, even tired from the trip!`,
  },
  {
    date: '2026-11-27',
    category: 'culture',
    topic_summary:
      'Black Friday in Brazil, and its joke name Black Fraude.',
    easy_target: `Hoje é Black Friday no Brasil. As lojas têm descontos, mas eu olho o preço com calma.`,
    easy_english: `Today is Black Friday in Brazil. The shops have discounts, but I look at the price calmly.`,
    medium_target: `A Black Friday veio dos Estados Unidos e hoje é uma das maiores datas de compras do ano no Brasil. As lojas anunciam muitos descontos, e muita gente compra pelo celular. Mas alguns brasileiros brincam e chamam o dia de Black Fraude, porque acham que certos descontos não são de verdade. Por isso, é bom comparar os preços antes de comprar.`,
    medium_english: `Black Friday came from the United States and today it is one of the biggest shopping dates of the year in Brazil. The shops announce many discounts, and many people buy on their phones. But some Brazilians joke and call the day Black Fraude, meaning Black Fraud, because they think certain discounts are not real. So it is good to compare prices before buying.`,
    hard_target: `A Black Friday nasceu nos Estados Unidos, no dia seguinte ao feriado de Ação de Graças. No Brasil, ela ficou popular há mais de dez anos, e muita gente espera essa data para comprar celular, roupa e eletrodomésticos. Muitas lojas anunciam o preço em parcelas, por exemplo dez vezes sem juros, um costume muito brasileiro. Só que muita gente desconfia dos descontos, e por isso surgiu a brincadeira Black Fraude. Antes, era mais difícil descobrir se um preço tinha realmente caído, mas hoje é fácil comparar tudo no celular. Eu vou olhar as ofertas com calma e não vou comprar nada por impulso. Se alguém na mesa fizer essa piada, eu vou rir e entender.`,
    hard_english: `Black Friday was born in the United States, on the day after the Thanksgiving holiday. In Brazil, it became popular more than ten years ago, and many people wait for this date to buy phones, clothes and appliances. Many shops advertise the price in instalments, for example ten instalments with no interest, a very Brazilian custom. But many people distrust the discounts, and that is why the joke Black Fraude, meaning Black Fraud, appeared. In the past, it was harder to find out whether a price had really dropped, but today it is easy to compare everything on your phone. I am going to look at the offers calmly and I am not going to buy anything on impulse. If someone at the table makes that joke, I am going to laugh and understand it.`,
  },
  {
    date: '2026-11-28',
    category: 'small_talk',
    topic_summary:
      'How to compliment the cook with Está uma delícia!, Estava ótimo! and Quem fez?',
    easy_target: `Nossa, Dona Márcia, está uma delícia, e eu quero mais um pouquinho! Quem fez este prato?`,
    easy_english: `Wow, Dona Márcia, it is delicious, and I would like a little more! Who made this dish?`,
    medium_target: `Quando a comida está boa, é bom dizer isso em voz alta, porque quem cozinha adora ouvir. Durante a refeição, você pode dizer: Está uma delícia! Depois de comer, diga: Estava ótimo! Se você quer saber quem fez o prato, pergunte: Quem fez? Depois, você pode pedir a receita com um sorriso.`,
    medium_english: `When the food is good, it is good to say so out loud, because the person who cooked loves to hear it. During the meal, you can say: It is delicious! After eating, say: It was great! If you want to know who made the dish, ask: Who made it? Afterwards, you can ask for the recipe with a smile.`,
    hard_target: `No Brasil, elogiar a comida é uma das melhores formas de agradecer a quem cozinhou. Durante a refeição, o elogio vem no presente: Está uma delícia! Depois de terminar, ele vai para o passado: Estava ótimo! Também é normal perguntar quem fez o prato, e a resposta quase sempre vem com orgulho. Todo cozinheiro que já recebeu um elogio sincero sabe que a alegria dura o dia inteiro. Se o prato for especial, a pessoa vai contar a história da receita, e você pode pedir uma cópia. Na casa de Dona Márcia, eu vou comer com calma, elogiar de coração e repetir uma vez.`,
    hard_english: `In Brazil, praising the food is one of the best ways to thank the person who cooked. During the meal, the compliment comes in the present tense: It is delicious! After finishing, it goes into the past: It was great! It is also normal to ask who made the dish, and the answer almost always comes with pride. Every cook who has ever received a sincere compliment knows that the joy lasts the whole day. If the dish is special, the person is going to tell the story of the recipe, and you can ask for a copy. At Dona Márcia's house, I am going to eat calmly, compliment from the heart and have seconds once.`,
  },
  {
    date: '2026-11-29',
    category: 'city',
    topic_summary:
      "Parque Ibirapuera, São Paulo's big park for Sunday walks, bikes and picnics.",
    easy_target: `O Parque Ibirapuera é grande. No domingo, as pessoas caminham, andam de bicicleta e fazem piquenique.`,
    easy_english: `Ibirapuera Park is big. On Sunday, people walk, ride bikes and have picnics.`,
    medium_target: `O Parque Ibirapuera é o parque mais conhecido de São Paulo. Ele é grande e tem lago, árvores, ciclovia e muitos gramados. Aos domingos, muitas famílias caminham, andam de bicicleta e fazem piquenique. Eu quero passear lá com Dani e tomar um suco de laranja na grama.`,
    medium_english: `Ibirapuera Park is the best-known park in São Paulo. It is big and has a lake, trees, a bike path and many lawns. On Sundays, many families walk, ride bikes and have picnics. I want to stroll there with Dani and drink an orange juice on the grass.`,
    hard_target: `O Parque Ibirapuera foi inaugurado em 1954, quando a cidade de São Paulo estava comemorando quatrocentos anos. Os prédios do parque foram desenhados por Oscar Niemeyer, um dos arquitetos mais famosos do Brasil. Hoje ele é um dos lugares preferidos dos paulistanos para escapar do barulho da cidade. Aos domingos, o parque enche de gente que corre, anda de bicicleta, toca violão ou estende uma toalha na grama. Eu já vi fotos do parque e fiquei com vontade de conhecer. Se o tempo estiver bom, eu vou caminhar lá com Dani, levar um lanche e sentar na grama. Em dezembro faz calor e muitas vezes chove no fim da tarde, então vou levar um guarda-chuva.`,
    hard_english: `Ibirapuera Park was opened in 1954, when the city of São Paulo was celebrating four hundred years. The park's buildings were designed by Oscar Niemeyer, one of the most famous architects in Brazil. Today it is one of the favourite places of São Paulo people for escaping the noise of the city. On Sundays, the park fills with people who run, ride bikes, play guitar or spread out a towel on the grass. I have already seen photos of the park and felt like visiting. If the weather is good, I am going to walk there with Dani, bring a snack and sit on the grass. In December it is hot and it often rains late in the afternoon, so I am going to bring an umbrella.`,
  },
  {
    date: '2026-11-30',
    category: 'holidays',
    topic_summary:
      'How Christmas lights and decorations appear in December in Brazilian homes, shops and on Avenida Paulista.',
    easy_target: `Dezembro está chegando, e as casas e as lojas já têm luzes de Natal. Eu chego a São Paulo no dia 20 de dezembro!`,
    easy_english: `December is coming, and houses and shops already have Christmas lights. I arrive in São Paulo on 20 December!`,
    medium_target: `Em dezembro, o Natal chega ao Brasil com muita luz e muita cor. As lojas, os shoppings e as casas colocam árvore de Natal e pisca-pisca. Na Avenida Paulista, geralmente tem luzes e decoração de Natal. Como é verão, o Natal é quente, e a ceia da noite do dia 24 pode ter peru, farofa e panetone.`,
    medium_english: `In December, Christmas arrives in Brazil with lots of light and colour. Shops, malls and houses put up a Christmas tree and twinkling lights. On Avenida Paulista, there are usually lights and Christmas decorations. Since it is summer, Christmas is hot, and the dinner on the night of the 24th may have turkey, farofa and panettone.`,
    hard_target: `Dezembro está chegando, e o clima de Natal já começou no Brasil. Nas últimas semanas, as lojas, os shoppings e muitas casas colocaram árvores e pisca-pisca. Na Avenida Paulista, em São Paulo, costuma haver luzes e decoração de Natal, e muita gente passeia por lá à noite. Como o Natal cai no verão, as pessoas usam roupa leve, e quase ninguém precisa de casaco. A principal festa é a ceia da noite do dia 24, com peru, farofa, rabanada e panetone. Muitas famílias abriam os presentes à meia-noite e ainda fazem isso hoje. No dia 20, quando eu chegar, ainda vão faltar cinco dias para o Natal, então vou poder ver as luzes.`,
    hard_english: `December is coming, and the Christmas mood has already begun in Brazil. In recent weeks, shops, malls and many houses have put up trees and twinkling lights. On Avenida Paulista, in São Paulo, there are usually lights and Christmas decorations, and many people stroll there at night. Since Christmas falls in summer, people wear light clothes, and almost nobody needs a coat. The main celebration is the dinner on the night of the 24th, with turkey, farofa, rabanada and panettone. Many families used to open their presents at midnight, and they still do that today. On the 20th, when I arrive, there will still be five days left until Christmas, so I will be able to see the lights.`,
  },
];
